name: Crowdin Download

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 */12 * * *' # Every 12 hours

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin pull
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_sources: true
          download_translations: true
          create_pull_request: false
          push_translations: true
          download_translations_args: -b main
          localization_branch_name: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
